version: '3.8'
name: hie
services:
  mysql:
    image: mysql:latest
    container_name: mysql_lab1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: user
      MYSQL_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  flask-app:
    build:
      context: "./app"
      dockerfile: Dockerfile
    container_name: flask_lab1
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file:
      - .env
